services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/sartre-db
    depends_on:
      - postgres-db
    networks:
      - sartre-network
    ports:
      - '3000:3000'

  postgres-db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sartre-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sartre-network
    ports:
      - '5432:5432'

networks:
  sartre-network:
    driver: bridge

volumes:
  postgres-data:
